const CONFIG={MODE:"Cloud",SHEET_URL_SCHEDULE_CSV:"%%SCHEDULE_CSV_URL%%",SHEET_URL_HOLIDAY_CSV:"%%HOLIDAY_CSV_URL%%",API_URL:"%%APPS_SCRIPT_URL%%"};
const qs=s=>document.querySelector(s);const fmt=d=>new Date(d).toISOString().slice(0,10);
function upcomingTwoQuartersFromToday(){const t=new Date();const y=t.getFullYear();const m=t.getMonth();const q=Math.floor(m/3);const qRange=(Y,Q)=>{const s=Q*3;return[new Date(Y,s,1),new Date(Y,s+3,0)]};const [q1s,q1e]=qRange(y,q);const n=(q+1)%4;const y2=n<q?y+1:y;const [q2s,q2e]=qRange(y2,n);return{q1s,q1e,q2s,q2e}}
function sundaysBetween(s,e){const a=[];let d=new Date(s);d.setDate(d.getDate()+((7-d.getDay())%7));while(d<=e){a.push(fmt(d));d.setDate(d.getDate()+7)}return a}
async function fetchCSV(u){const r=await fetch(u);if(!r.ok)throw new Error("fetch failed");const t=await r.text();const rows=t.trim().split(/\r?\n/).map(r=>r.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/));const h=rows.shift().map(x=>x.trim().toLowerCase());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||"").replace(/^"|"$/g,"")])))}
function readLocal(){const key='DAUNTLESS_LOCAL_DATA';let data=JSON.parse(localStorage.getItem(key)||'null');if(!data){data={schedule:[{date:'2025-11-09',league:'TSAA',status:'已排',note:''},{date:'2025-12-07',league:'TSAA',status:'已排',note:''},{date:'2026-01-11',league:'TSAA',status:'需避開',note:'連假'}],holiday:[{date:'2026-01-01',type:'國定假日'},{date:'2026-02-28',type:'國定假日'}]};localStorage.setItem(key,JSON.stringify(data))}return data}
async function readData(){if(CONFIG.MODE==='Cloud'&&CONFIG.SHEET_URL_SCHEDULE_CSV.startsWith('http')){const s=await fetchCSV(CONFIG.SHEET_URL_SCHEDULE_CSV);const h=CONFIG.SHEET_URL_HOLIDAY_CSV.startsWith('http')?await fetchCSV(CONFIG.SHEET_URL_HOLIDAY_CSV):[];return{schedule:s.map(x=>({date:x.date||x['日期'],league:x.league||x['聯盟']||'TSAA',status:x.status||x['狀態']||'已排',note:x.note||x['備註']||''})),holiday:h.map(x=>({date:x.date||x['日期'],type:x.type||x['類型']||'連假'}))}}else{return readLocal()}}
function renderSlots(el,sundays,map,avoid){el.innerHTML='';sundays.forEach(d=>{const div=document.createElement('div');div.className='slot';const booked=map.has(d);const tags=[];if(booked)tags.push('<span class="tag green">已排</span>');if(avoid.has(d))tags.push('<span class="tag red">避開</span>');div.innerHTML=`<div class="left"><span class="dot"></span><div><div class="date">${new Date(d).toLocaleDateString('zh-TW',{month:'2-digit',day:'2-digit'})}</div><div class="range">${d}</div></div></div><div class="tags">${tags.join('')}</div>`;el.appendChild(div)})}
function computeAvoidSet(data){const set=new Set();data.schedule.forEach(s=>{if((s.status||'')==='需避開')set.add(s.date)});data.holiday.forEach(h=>{const d=new Date(h.date);if(d.getDay()===0)set.add(fmt(d))});return set}
async function bootstrap(){qs('#srcLabel').textContent=(CONFIG.MODE==='Cloud'&&CONFIG.SHEET_URL_SCHEDULE_CSV.startsWith('http'))?'雲端':'本機';const {q1s,q1e,q2s,q2e}=upcomingTwoQuartersFromToday();qs('#q1Title').textContent=`本季（日） ${q1s.toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit'})} ~ ${q1e.toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit'})}`;qs('#q2Title').textContent=`次季（日） ${q2s.toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit'})} ~ ${q2e.toLocaleDateString('zh-TW',{year:'numeric',month:'2-digit'})}`;const s1=sundaysBetween(q1s,q1e);const s2=sundaysBetween(q2s,q2e);qs('#k_total').textContent=String(s1.length+s2.length);const data=await readData();const map=new Map(data.schedule.filter(s=>s.status==='已排').map(s=>[s.date,s]));const avoid=computeAvoidSet(data);qs('#k_q1').textContent=String(s1.filter(d=>map.has(d)).length);qs('#k_q2').textContent=String(s2.filter(d=>map.has(d)).length);qs('#k_avoid').textContent=String(new Set([...s1,...s2].filter(d=>avoid.has(d))).size);renderSlots(qs('#q1List'),s1,map,avoid);renderSlots(qs('#q2List'),s2,map,avoid);const avoidList=[...new Set([...s1,...s2].filter(d=>avoid.has(d)))].map(d=>new Date(d).toLocaleDateString('zh-TW',{month:'2-digit',day:'2-digit'})).join('、');qs('#avoidList').textContent=avoidList||'（本雙季無需避開的週日）'}
document.addEventListener('DOMContentLoaded',()=>{bootstrap().catch(e=>alert('讀取失敗：'+e.message));let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});qs('#btnInstall').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}});qs('#btnReload').addEventListener('click',()=>location.reload());qs('#btnAvoid').addEventListener('click',()=>qs('#avoidDlg').showModal());qs('#btnNew').addEventListener('click',()=>{qs('#f_date').value=new Date().toISOString().slice(0,10);qs('#f_league').value='TSAA';qs('#f_status').value='已排';qs('#f_note').value='';qs('#editDlg').showModal()});qs('#btnSave').addEventListener('click',async ev=>{ev.preventDefault();const payload={date:qs('#f_date').value,league:qs('#f_league').value,status:qs('#f_status').value,note:qs('#f_note').value};if(new Date(payload.date).getDay()!==0){alert('請選擇「星期日」日期。');return}try{if(CONFIG.API_URL.startsWith('http')){const res=await fetch(CONFIG.API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('寫入失敗（GAS 回應非 200）');alert('已寫入雲端表格。');location.reload()}else{const store=(function(){const key='DAUNTLESS_LOCAL_DATA';let d=JSON.parse(localStorage.getItem(key)||'null');if(!d){d={schedule:[],holiday:[]}};return {get:()=>JSON.parse(localStorage.getItem(key)||JSON.stringify(d)),save:x=>localStorage.setItem(key,JSON.stringify(x))}})();const s=store.get();const i=s.schedule.findIndex(x=>x.date===payload.date);if(i>=0)s.schedule[i]=payload;else s.schedule.push(payload);store.save(s);alert('已寫入本機（測試模式）。');location.reload()}}catch(e){alert('寫入失敗：'+e.message)}})});
